name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up git user
        run: |
          git config --global user.email "krishnaguptakrishnbly@gmail.com"
          git config --global user.name "Krishna-Gupta989"

      - name: Remove deleted large files from history
        run: |
          git filter-branch --force --index-filter "git rm --cached --ignore-unmatch prices.zip" --prune-empty --tag-name-filter cat -- --all

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://KrishnaGupta989:${HF_TOKEN}@huggingface.co/spaces/KrishnaGupta989/stock-predictor-app || echo "remote exists"
          git push hf main --force
