name: Sync to Hugging Face hub

on:
  push:
    branches: [main]  # Trigger on push to main branch
  workflow_dispatch:   # Also allow manual trigger

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up git user
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://KrishnaGupta989:${HF_TOKEN}@huggingface.co/spaces/KrishnaGupta989/stock-predictor-app
          git push hf main --force
